AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: meli full sales lambda

Globals:
  Function:
    Timeout: 20

Resources:
  MeliFullSalesFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: 'applications-db'
        - SQSSendMessagePolicy:
            QueueName: !ImportValue TelegramMessageQueueName
      Environment:
        Variables:
          SQS_QUEUE_URL: !ImportValue TelegramMessageQueueUrl
          ENVIRONMENT: prod
      Events:
        MeliFullSalesSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)'
            Name: MeliFullSalesSchedule
            Description: Meli full sales schedule
            Enabled: true
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile
