name: Deploy to development 

on:
  push:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY_2}}
        heroku_app_name: "meli-full-sales-dev"
        heroku_email: "pablofelitti@gmail.com"
        usedocker: true
        docker_build_args: |
            TELEGRAM_BOT_TOKEN
            TELEGRAM_CHANNEL
            PGHOST
            PGDATABASE
            PGPASSWORD
            PGUSER
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_DEV }}
        TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL_DEV }}
        PGHOST: ${{ secrets.PGHOST_DEV }}
        PGDATABASE: ${{ secrets.PGDATABASE_DEV }}
        PGPASSWORD: ${{ secrets.PGPASSWORD_DEV }}
        PGUSER: ${{ secrets.PGUSER_DEV }}