name: Deploy to production server

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "meli-full-sales-prod"
        heroku_email: "pablofelitti@gmail.com"
        usedocker: true
        docker_build_args: |
            MELI_CRON
            TELEGRAM_BOT_TOKEN
            TELEGRAM_CHANNEL
            PGHOST
            PGDATABASE
            PGPASSWORD
            PGUSER
      env:
        MELI_CRON: "* * * * *"
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_PROD }}
        TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL_PROD }}
        PGHOST: ${{ secrets.PGHOST_PROD }}
        PGDATABASE: ${{ secrets.PGDATABASE_PROD }}
        PGPASSWORD: ${{ secrets.PGPASSWORD_PROD }}
        PGUSER: ${{ secrets.PGUSER_PROD }}
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY_2}}
        heroku_app_name: "meli-full-sales-prod"
        heroku_email: "pablofelitti@gmail.com"
        usedocker: true
        docker_build_args: |
            MELI_CRON
            TELEGRAM_BOT_TOKEN
            TELEGRAM_CHANNEL
            PGHOST
            PGDATABASE
            PGPASSWORD
            PGUSER
      env:
        MELI_CRON: "30 * * * * *"
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_2_PROD }}
        TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL_PROD }}
        PGHOST: ${{ secrets.PGHOST_PROD }}
        PGDATABASE: ${{ secrets.PGDATABASE_PROD }}
        PGPASSWORD: ${{ secrets.PGPASSWORD_PROD }}
        PGUSER: ${{ secrets.PGUSER_PROD }}